# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.10.0
_src_path: gh:radio-aktywne/template-meta
accountname: radio-aktywne
description: Python package template 🐍
reponame: template-package-python
repourl: https://github.com/radio-aktywne/template-package-python
templatename: python
type: package
